version: 1
update_configs:
- package_manager: "dotnet:nuget"
  directory: /
  update_schedule: live
  default_assignees:
  - mynkow
  default_reviewers:
  - mynkow
  default_labels:
  - dependencies
  allowed_updates:
  - match:
      update_type: all
      dependency_type: direct
  - match:
      update_type: all
      dependency_type: indirect
  target_branch: release-*
